### ISSUE TITLE
Link for model suggestion gives error

### ISSUE THREAD

**Issue by Aakanksha-Rana** [neuronets/zoo#17]
Link directs here: https://github.com/neuronets/zoo/blob/main and Page not found error appears.

**Comment by Hoda1394** [comment]
I wanted to create an issue template for it but the repository setting does not show the issue part. 
@satra, would you check the repository setting?
if it cannot be fixed I will change the readme.

**Comment by satra** [comment]
what do you mean by settings? templates for issues are created in the repo itself, under `.github`. here is an example. and you click on new issue in that repo to see what it does.

https://github.com/nipreps/fmriprep/tree/master/.github/ISSUE_TEMPLATE

**Comment by Hoda1394** [comment]
Thanks.
By the way, by repo setting, I mean this.
[https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by satra** [comment]
you may still be able to do this with this link: https://github.com/neuronets/zoo/issues/templates/edit
